name: Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          - iris-agent
          - iris-api
          - iris-worker
    steps:
      - uses: actions/checkout@v2
      - uses: dioptra-io/publish-docker-action@v1.3
        with:
          file: ./dockerfiles/${{ matrix.image }}.dockerfile
          image: dioptra-io/iris/${{ matrix.image }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # platforms: linux/amd64,linux/arm64
